/*
 * Kanonische Vorlagen und illustrative Simulationsparameter.
 *
 * Kanonisch sind: Namen, beobachtbare Richtungen, Einheiten, der 46.080-Um-
 * Konvektionszyklus sowie die 400-Um-Konvektion. Zahlenbereiche für Geschwindigkeit,
 * Intensität und Einzeldauer dienen ausschließlich der sechsminütigen Darstellung.
 */
(function defineEraPhases(global) {
  "use strict";

  const UM_PER_TAN = 16;
  const TAN_PER_DIR = 8;
  const DIR_PER_MOHN = 36;
  const MOHN_PER_CYCLE = 10;
  const CONVECTION_DURATION_UM = 400;
  const TOTAL_UM = UM_PER_TAN * TAN_PER_DIR * DIR_PER_MOHN * MOHN_PER_CYCLE;

  const CONFIG = Object.freeze({
    umPerTan: UM_PER_TAN,
    tanPerDir: TAN_PER_DIR,
    dirPerMohn: DIR_PER_MOHN,
    mohnPerCycle: MOHN_PER_CYCLE,
    earthMinutesPerUm: 90,
    idealLightMinutesPerUm: 45,
    idealDarkMinutesPerUm: 45,
    totalUm: TOTAL_UM,
    regularUm: TOTAL_UM - CONVECTION_DURATION_UM,
    convectionDurationUm: CONVECTION_DURATION_UM,
    eraRotationDegreesPerSecond: 5.6,
    presentationMs: 360000,
    convectionPresentationMs: 32000,
    minRepeatedTemplates: 12,
    maxRepeatedTemplates: 18,
    schemaVersion: 3,
  });

  const CATEGORIES = Object.freeze([
    { id: "synchron", label: "Synchron", color: "#8f68d7", icon: "icon-category-synchron" },
    { id: "langsam", label: "Langsam", color: "#3f91ad", icon: "icon-category-langsam" },
    { id: "stehend", label: "Stehende Sonnen", color: "#8a8173", icon: "icon-category-stehend" },
    { id: "asynchron", label: "Asynchron", color: "#c4653f", icon: "icon-category-asynchron" },
    { id: "wechselnd", label: "Wechselnd", color: "#ad55b8", icon: "icon-category-wechselnd" },
    { id: "konvektion", label: "Konvektion", color: "#c64d43", icon: "icon-category-konvektion" },
  ]);

  const body = (speed, intensity, options = {}) =>
    Object.freeze({
      speed: Object.freeze(speed),
      intensity: intensity ? Object.freeze(intensity) : null,
      visible: options.visible !== false,
      radialAmplitude: options.radialAmplitude || 0,
    });

  const synchronizedBody = (intensity, options = {}) =>
    body(
      [CONFIG.eraRotationDegreesPerSecond, CONFIG.eraRotationDegreesPerSecond],
      intensity,
      options,
    );

  const templates = [
    {
      id: "sync-standing",
      icon: "icon-sync-standing",
      category: "synchron",
      label: "Stehend synchron",
      shortLabel: "Stehend sync.",
      description: "Der Himmelskörper hält über längere Zeit annähernd dieselbe sichtbare Stellung.",
      direction: "Ost → West · annähernd ortsfest",
      motion: "hold",
      sol: synchronizedBody([3.5, 8.5]),
      yol: synchronizedBody([2.5, 8.0]),
      repeatWeight: 1.1,
      durationWeight: 1.0,
    },
    {
      id: "sync-morning-evening",
      icon: "icon-sync-morning-evening",
      category: "synchron",
      label: "Morgen- und Abendsynchron",
      shortLabel: "Morgen/Abend",
      description: "Sol oder Yol bleibt an einen lang anhaltenden Morgen- beziehungsweise Abendbereich gebunden.",
      direction: "Ost → West · horizontnah",
      motion: "horizon",
      sol: synchronizedBody([2.0, 7.0], { radialAmplitude: 8 }),
      yol: synchronizedBody([2.0, 7.5], { radialAmplitude: 7 }),
      repeatWeight: 1.0,
      durationWeight: 1.05,
    },
    {
      id: "sync-long-night-morning",
      icon: "icon-sync-long-night-morning",
      category: "synchron",
      label: "Langer Nachtmorgen / lange Abenddämmerung",
      shortLabel: "Nachtmorgen",
      description: "Der Übergangsbereich am Rand einer langen Nacht- oder Abendphase bleibt bestehen.",
      direction: "Ost → West · gedehnter Übergang",
      motion: "horizon",
      sol: synchronizedBody([1.5, 5.5], { radialAmplitude: 11 }),
      yol: synchronizedBody([4.0, 9.0], { radialAmplitude: 8 }),
      repeatWeight: 0.9,
      durationWeight: 1.2,
    },
    {
      id: "sync-long-morning",
      icon: "icon-sync-long-morning",
      category: "synchron",
      label: "Langer Morgen / lange Dämmerung",
      shortLabel: "Lange Dämmerung",
      description: "Auf- oder Untergang zieht sich aus Sicht der Region stark in die Länge.",
      direction: "Ost → West · langsamer Auf-/Untergang",
      motion: "horizon",
      sol: synchronizedBody([2.5, 8.5], { radialAmplitude: 10 }),
      yol: synchronizedBody([2.5, 8.0], { radialAmplitude: 10 }),
      repeatWeight: 0.9,
      durationWeight: 1.15,
    },
    {
      id: "sync-wandering",
      icon: "icon-sync-wandering",
      category: "synchron",
      label: "Wandernd synchron",
      shortLabel: "Wandernd sync.",
      description: "Der Himmelskörper verschiebt sich langsam weiter, ohne die synchrone Richtung zu verlassen.",
      direction: "Ost → West",
      motion: "orbit",
      sol: synchronizedBody([2.0, 9.0], { radialAmplitude: 6 }),
      yol: synchronizedBody([2.0, 9.0], { radialAmplitude: 5 }),
      repeatWeight: 1.5,
      durationWeight: 0.9,
    },
    {
      id: "sync-oscillating",
      icon: "icon-sync-oscillating",
      category: "synchron",
      label: "Schwankender Morgen / Abend",
      shortLabel: "Schwankend",
      description: "Die sichtbare Stellung pendelt innerhalb eines Morgen- oder Abendbereichs.",
      direction: "Ost ↔ West · begrenztes Pendeln",
      motion: "oscillate",
      sol: synchronizedBody([2.0, 9.0], { radialAmplitude: 12 }),
      yol: synchronizedBody([2.0, 9.0], { radialAmplitude: 10 }),
      repeatWeight: 1.2,
      durationWeight: 1.0,
    },
    {
      id: "sync-short-day",
      icon: "icon-sync-short-day",
      category: "synchron",
      label: "Kurzer Tag und lange Nacht",
      shortLabel: "Kurzer Tag",
      description: "Eine kurze Sol-Phase liegt zwischen deutlich längeren Yol- oder Dunkelphasen.",
      direction: "Ost → West · mit Era synchron",
      motion: "short-sol",
      sol: synchronizedBody([3.0, 10.0]),
      yol: synchronizedBody([3.5, 9.5]),
      repeatWeight: 0.85,
      durationWeight: 0.8,
    },
    {
      id: "sync-short-night",
      icon: "icon-sync-short-night",
      category: "synchron",
      label: "Kurze Nacht und langer Tag",
      shortLabel: "Kurze Nacht",
      description: "Eine kurze Yol- oder Dunkelphase liegt zwischen deutlich längeren Sol-Phasen.",
      direction: "Ost → West · mit Era synchron",
      motion: "short-yol",
      sol: synchronizedBody([4.0, 10.0]),
      yol: synchronizedBody([2.0, 9.0]),
      repeatWeight: 0.85,
      durationWeight: 0.8,
    },
    {
      id: "slow-day-night",
      icon: "icon-slow-day-night",
      category: "langsam",
      label: "Tag-Nacht-Lauf",
      shortLabel: "Tag/Nacht",
      description: "Ein vollständiger beobachtbarer Wechsel von Tag zu Nacht und zurück bildet den Bezugsbereich.",
      direction: "Langsamer sichtbarer Wechsel",
      motion: "orbit",
      sol: body([1.2, 3.2], [1.5, 9.5], { radialAmplitude: 7 }),
      yol: body([1.0, 3.0], [1.5, 9.5], { radialAmplitude: 7 }),
      repeatWeight: 1.1,
      durationWeight: 1.15,
    },
    {
      id: "slow-normal",
      icon: "icon-slow-normal",
      category: "langsam",
      label: "Normallauf",
      shortLabel: "Normallauf",
      description: "Vergleichsbereich für einen langsamen Lauf, der nicht fest an Tan oder Dir gebunden ist.",
      direction: "Langsam · Richtung szenarioabhängig",
      motion: "orbit",
      sol: body([1.5, 4.0], [2.0, 9.0], { radialAmplitude: 5 }),
      yol: body([1.3, 3.8], [2.0, 9.0], { radialAmplitude: 5 }),
      repeatWeight: 1.5,
      durationWeight: 1.0,
    },
    {
      id: "slow-tan",
      icon: "icon-slow-tan",
      category: "langsam",
      label: "Tan-Lauf",
      shortLabel: "Tan-Lauf",
      description: "Der maßgebliche Verlauf liegt auf der Größenordnung von Tan; die konkrete Dauer bleibt illustrativ.",
      direction: "Langsam · Tan-Größenordnung",
      motion: "orbit",
      sol: body([1.0, 2.8], [2.0, 9.5]),
      yol: body([0.9, 2.6], [2.0, 9.0]),
      repeatWeight: 1.15,
      durationWeight: 0.75,
    },
    {
      id: "slow-dir",
      icon: "icon-slow-dir",
      category: "langsam",
      label: "Dir-Lauf",
      shortLabel: "Dir-Lauf",
      description: "Der maßgebliche Verlauf liegt auf der Größenordnung von Dir; die konkrete Dauer bleibt illustrativ.",
      direction: "Langsam · Dir-Größenordnung",
      motion: "orbit",
      sol: body([0.65, 2.1], [2.0, 9.5]),
      yol: body([0.6, 1.9], [2.0, 9.0]),
      repeatWeight: 1.0,
      durationWeight: 1.35,
    },
    {
      id: "standing-suns",
      icon: "icon-standing-suns",
      category: "stehend",
      label: "Stehende Sonnen",
      shortLabel: "Stehende Sonnen",
      description: "Sol oder Yol steht relativ zur eigenen Umlaufbahn; Eras Rotation erzeugt den sichtbaren Wechsel.",
      direction: "Umlauf annähernd stehend · Era rotiert",
      motion: "fixed-orbit",
      sol: body([0.05, 0.3], [2.0, 9.0]),
      yol: body([0.05, 0.3], [2.0, 9.0]),
      repeatWeight: 0.85,
      durationWeight: 1.1,
    },
    {
      id: "async-wandering",
      icon: "icon-async-wandering",
      category: "asynchron",
      label: "Wandernd asynchron",
      shortLabel: "Wandernd async.",
      description: "Der Himmelskörper zieht entgegen der üblichen Richtung über den sichtbaren Himmel.",
      direction: "West → Ost",
      motion: "reverse",
      sol: body([5.5, 11.0], [2.0, 10.0], { radialAmplitude: 5 }),
      yol: body([5.0, 10.0], [2.0, 10.0], { radialAmplitude: 5 }),
      repeatWeight: 1.35,
      durationWeight: 0.8,
    },
    {
      id: "async-horizon",
      icon: "icon-async-horizon",
      category: "asynchron",
      label: "Wandernd asynchron am Horizont",
      shortLabel: "Async. Horizont",
      description: "Die Gegenbewegung bleibt flach und horizontnah; kleine Erhebungen können den Körper verdecken.",
      direction: "West → Ost · horizontnah",
      motion: "reverse-horizon",
      sol: body([4.5, 9.0], [1.5, 8.5], { radialAmplitude: 14 }),
      yol: body([4.0, 8.5], [1.5, 8.5], { radialAmplitude: 12 }),
      repeatWeight: 0.95,
      durationWeight: 0.85,
    },
    {
      id: "async-parabola",
      icon: "icon-async-parabola",
      category: "asynchron",
      label: "Asynchroner Parabellauf",
      shortLabel: "Parabellauf",
      description: "Die sichtbare Bahn steigt bogenförmig an und fällt wieder ab; die Gegenrichtung bleibt erhalten.",
      direction: "West → Ost · bogenförmig",
      motion: "parabola",
      sol: body([6.0, 12.0], [2.0, 10.0], { radialAmplitude: 34 }),
      yol: body([5.5, 11.0], [2.0, 10.0], { radialAmplitude: 30 }),
      repeatWeight: 0.8,
      durationWeight: 0.9,
    },
    {
      id: "changing",
      icon: "icon-changing",
      category: "wechselnd",
      label: "Wechselnde Phasen",
      shortLabel: "Wechselnd",
      description: "Häufigstes Meta-Regime: abrupte Wechsel zwischen synchronen, langsamen, stehenden und asynchronen Zuständen.",
      direction: "Wechselnd · abrupte Umkehr möglich",
      motion: "switching",
      sol: body([0.5, 13.0], [1.0, 10.0], { radialAmplitude: 20 }),
      yol: body([0.5, 12.5], [1.0, 10.0], { radialAmplitude: 18 }),
      repeatWeight: 8.0,
      durationWeight: 4.8,
    },
    {
      id: "convection",
      icon: "icon-convection",
      category: "konvektion",
      label: "Konvektion",
      shortLabel: "Konvektion",
      description: "400 Um bittere Dunkelheit: Sol und Yol sind nicht sichtbar; Splitterwelten und Sphärenreiche Heras treten hervor.",
      direction: "Kein sichtbarer Sonnenlauf",
      motion: "convection",
      sol: body([0, 0], null, { visible: false }),
      yol: body([0, 0], null, { visible: false }),
      repeatWeight: 0,
      durationWeight: 0,
    },
  ].map((template) =>
    Object.freeze({
      ...template,
      sol: template.sol,
      yol: template.yol,
    }),
  );

  global.ERA_PHASES = Object.freeze({
    config: CONFIG,
    categories: CATEGORIES,
    templates: Object.freeze(templates),
  });
})(window);
